name: Discord Rich Presence Activity Badge

on:
  schedule:
    - cron: "5 0-23 * * *"

  workflow_dispatch:

jobs:
  BadgeUpdater:
    name: Static Badge Updater
    runs-on: ubuntu-latest

    steps:
      - name: Update README Discord Badge to Latest Upstream
        uses: CodexLink/discord-activity-badge@v1.0
        with:
          BADGE_IDENTIFIER_NAME: activity
          DISCORD_USER_ID: ${{ secrets.DISCORD_USER_ID }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
