name: Waka Readme

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    # runs-on: apex
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          # LOCALE: ""
          # SECTION_NAME: ""
          COMMIT_BY_ME: true
          # COMMIT_MESSAGE: ""
          # COMMIT_USERNAME: ""
          # COMMIT_EMAIL: ""
          SHOW_UPDATED_DATE: true
          # UPDATED_DATE_FORMAT: ""
          SHOW_LINES_OF_CODE: true
          SHOW_TOTAL_CODE_TIME: true
          SHOW_PROFILE_VIEWS: false
          SHOW_COMMIT: true
          SHOW_DAYS_OF_WEEK: false
          SHOW_LANGUAGE: true
          SHOW_OS: false
          SHOW_PROJECTS: true
          SHOW_TIMEZONE: false
          SHOW_EDITORS: false
          SHOW_LANGUAGE_PER_REPO: false
          SHOW_SHORT_INFO: false
          SHOW_LOC_CHART: false
          IGNORED_REPOS: "gradle"
          SYMBOL_VERSION: 2
          DEBUG_LOGGING: true
